---
version: 2.1

py38: &py38
  docker:
    - image: circleci/python:3.8.3
  working_directory: ~/gcs-s3-transfer-service

commands:
  run_tox:
    description: Install and run tox with a given environment
    parameters:
      toxenv:
        description: The name of the environment as per tox.ini, e.g. py38 or lint
        type: string
      extra_args:
        description: Extra arguments that are consumed only when running pytest
        type: string
        default: ''
    steps:
      - run: sudo pip install tox
      - run: tox -e << parameters.toxenv >> -- << parameters.extra_args >>

jobs:
  lint:
    <<: *py38
    steps:
      - checkout
      - run_tox:
          toxenv: lint
  test_py38:
    <<: *py38
    steps:
      - checkout
      - run_tox:
          toxenv: py38
          extra_args: -vv
  coverage_report:
    <<: *py38
    steps:
      - checkout
      - run_tox:
          toxenv: coverage-report

workflows:
  main:
    jobs:
      - lint
      - test_py38:
          requires:
            - lint
      - coverage_report:
          requires:
            - lint
